In [1]:

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
df=pd.read_csv("Loan Prediction Dataset.csv")
df

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [4]:
df=df.drop(columns="Dependents")
df

,Loan_ID,Gender,Married,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [8]:
df['Loan_ID']=df['Loan_ID'].astype('category')
df['Loan_ID']=df['Loan_ID'].cat.codes
df['Gender']=df['Gender'].astype('category')
df['Gender']=df['Gender'].cat.codes
df['Married']=df['Married'].astype('category')
df['Married']=df['Married'].cat.codes
df['Education']=df['Education'].astype('category')
df['Education']=df['Education'].cat.codes
df['Self_Employed']=df['Self_Employed'].astype('category')
df['Self_Employed']=df['Self_Employed'].cat.codes
df['Property_Area']=df['Property_Area'].astype('category')
df['Property_Area']=df['Property_Area'].cat.codes
df['Loan_Status']=df['Loan_Status'].astype('category')
df['Loan_Status']=df['Loan_Status'].cat.codes
df

,Loan_ID,Gender,Married,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,0,2,1,0,0,5849,0.0,NaN,360.0,1.0,2,1
1,1,2,2,0,0,4583,1508.0,128.0,360.0,1.0,0,0
2,2,2,2,0,1,3000,0.0,66.0,360.0,1.0,2,1
3,3,2,2,1,0,2583,2358.0,120.0,360.0,1.0,2,1
4,4,2,1,0,0,6000,0.0,141.0,360.0,1.0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...
609,609,1,1,0,0,2900,0.0,71.0,360.0,1.0,0,1
610,610,2,2,0,0,4106,0.0,40.0,180.0,1.0,0,1
611,611,2,2,0,0,8072,240.0,253.0,360.0,1.0,2,1
612,612,2,2,0,0,7583,0.0,187.0,360.0,1.0,2,1
613,613,1,1,0,1,4583,0.0,133.0,360.0,0.0,1,0

In [10]:
df.isnull().sum()

Loan_ID               0
Gender                0
Married               0
Education             0
Self_Employed         0
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [14]:
df=df.dropna()

In [15]:
df.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

In [17]:
X=df.drop(columns='Loan_Status')
X

,Loan_ID,Gender,Married,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
1,1,2,2,0,0,4583,1508.0,128.0,360.0,1.0,0
2,2,2,2,0,1,3000,0.0,66.0,360.0,1.0,2
3,3,2,2,1,0,2583,2358.0,120.0,360.0,1.0,2
4,4,2,1,0,0,6000,0.0,141.0,360.0,1.0,2
5,5,2,2,0,1,5417,4196.0,267.0,360.0,1.0,2
...,...,...,...,...,...,...,...,...,...,...,...
609,609,1,1,0,0,2900,0.0,71.0,360.0,1.0,0
610,610,2,2,0,0,4106,0.0,40.0,180.0,1.0,0
611,611,2,2,0,0,8072,240.0,253.0,360.0,1.0,2
612,612,2,2,0,0,7583,0.0,187.0,360.0,1.0,2
613,613,1,1,0,1,4583,0.0,133.0,360.0,0.0,1

In [18]:
y=df['Loan_Status']
y

1      0
2      1
3      1
4      1
5      1
      ..
609    1
610    1
611    1
612    1
613    0
Name: Loan_Status, Length: 529, dtype: int8

In [23]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=21)

In [24]:
len(X_train)

423

In [25]:
len(X_test)

106

In [22]:
len(df)

529

In [29]:
knn=KNeighborsClassifier(n_neighbors=1)
knn.fit(X_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [30]:
y_pred=knn.predict(X_test)

In [31]:
knn.score(X_train,y_train),knn.score(X_test,y_test)

(1.0, 0.6886792452830188)

In [32]:
knn=KNeighborsClassifier(n_neighbors=6)
knn.fit(X_train,y_train)
y_pred=knn.predict(X_test)
knn.score(X_train,y_train),knn.score(X_test,y_test)

(0.7092198581560284, 0.6415094339622641)

In [34]:
from sklearn.metrics import classification_report, confusion_matrix
confusion_matrix(y_test,y_pred)

array([[10, 24],
       [14, 58]])

In [35]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.42      0.29      0.34        34
           1       0.71      0.81      0.75        72

    accuracy                           0.64       106
   macro avg       0.56      0.55      0.55       106
weighted avg       0.61      0.64      0.62       106